class_name SpellBase
extends RefCounted

var id: String = ""
var display_name: String = ""
var noun: String = ""
var icon_id: String = ""
var description: String = ""
var available: bool = false
var max_infusions: int = 2
var delivery: AbilityDef.Delivery = AbilityDef.Delivery.BOLT
var target_mode: AbilityDef.TargetMode = AbilityDef.TargetMode.SKILLSHOT
var cost_per_tick: bool = false
var is_toggle: bool = false
var friendly_only: bool = false
var mana_cost: float = 50.0
var cooldown: float = 6.0
var range: float = 10.0
var damage: float = 80.0
var heal: float = 0.0
var shield: float = 0.0
var shield_duration: float = 0.0
var cast_time: float = 0.12
var color: Color = Color(0.55, 0.72, 1.0)
var skillshot_width: float = 0.9
var skillshot_speed: float = 18.0
var skillshot_length: float = 12.0
var aoe_radius: float = 2.5
var aoe_radius_max: float = 0.0
var damage_max: float = 0.0
var splash_radius: float = 0.0
var splash_ratio: float = 0.0
var cone_angle: float = 0.0
var chain_bounces: int = 0
var bounce_range: float = 6.0
var bounce_delay: float = 0.08
var is_channel: bool = false
var channel_time: float = 0.0
var zone_duration: float = 0.0
var tick_interval: float = 0.0
var tick_damage: float = 0.0
var tick_shield: float = 0.0
var gcd_exempt: bool = false
var vfx_scene: String = ""
var vfx_scale: float = 1.0
var vfx_yaw: float = 0.0
var vfx_primary: Color = Color(0, 0, 0, 0)
var vfx_secondary: Color = Color(0, 0, 0, 0)
var vfx_tertiary: Color = Color(0, 0, 0, 0)
